environment:
  matrix:
    - CMAKE_BUILD_TYPE: DEBUG
    - CMAKE_BUILD_TYPE: RELEASE

os:
  - Visual Studio 2015
  - Visual Studio 2017

platform:
  - x64

init:
  - cmd: set PATH=C:\Program Files (x86)\CMake\bin\;%PATH%

install:
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
  - git clone https://github.com/Microsoft/vcpkg
  - cd vcpkg
  - powershell -exec bypass scripts\bootstrap.ps1
  - vcpkg install zlib
  - vcpkg integrate install
  - cd ..

before_build:
  - cmd: cmake -B. -H.

build_script:
  - cmake --build . --config %CMAKE_BUILD_TYPE%